apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-tasks-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: brain-tasks-app
  template:
    metadata:
      labels:
        app: brain-tasks-app
    spec:
      containers:
      - name: brain-tasks-app
        image: 13482229768.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest  # Updated dynamically in pipeline
        ports:
        - containerPort: 3000
